# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apostleLastEditCEO.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1144, 712)
        Form.setSizeIncrement(QtCore.QSize(710, 510))
        Form.setBaseSize(QtCore.QSize(435, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/WhatsApp Image 2022-04-07 at 2.51.33 PM.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SlamLaunch = QtWidgets.QTabWidget(Form)
        self.SlamLaunch.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.SlamLaunch.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.SlamLaunch.setObjectName("SlamLaunch")
        self.Control = QtWidgets.QWidget()
        self.Control.setObjectName("Control")
        self.Speed_linear_x = QtWidgets.QSlider(self.Control)
        self.Speed_linear_x.setGeometry(QtCore.QRect(550, 20, 20, 511))
        self.Speed_linear_x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Speed_linear_x.setMinimum(-1000)
        self.Speed_linear_x.setMaximum(1000)
        self.Speed_linear_x.setSingleStep(10)
        self.Speed_linear_x.setPageStep(100)
        self.Speed_linear_x.setOrientation(QtCore.Qt.Vertical)
        self.Speed_linear_x.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Speed_linear_x.setTickInterval(0)
        self.Speed_linear_x.setObjectName("Speed_linear_x")
        self.angular_speed = QtWidgets.QSlider(self.Control)
        self.angular_speed.setGeometry(QtCore.QRect(80, 580, 961, 20))
        self.angular_speed.setMinimum(-1000)
        self.angular_speed.setMaximum(1000)
        self.angular_speed.setSingleStep(10)
        self.angular_speed.setPageStep(100)
        self.angular_speed.setOrientation(QtCore.Qt.Horizontal)
        self.angular_speed.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.angular_speed.setTickInterval(0)
        self.angular_speed.setObjectName("angular_speed")
        self.linear_stop = QtWidgets.QPushButton(self.Control)
        self.linear_stop.setGeometry(QtCore.QRect(490, 260, 41, 31))
        self.linear_stop.setObjectName("linear_stop")
        self.angular_stop = QtWidgets.QPushButton(self.Control)
        self.angular_stop.setGeometry(QtCore.QRect(540, 610, 41, 31))
        self.angular_stop.setObjectName("angular_stop")
        self.control_combo_box = QtWidgets.QComboBox(self.Control)
        self.control_combo_box.setGeometry(QtCore.QRect(970, 20, 131, 25))
        self.control_combo_box.setObjectName("control_combo_box")
        self.control_combo_box.addItem("")
        self.control_combo_box.addItem("")
        self.linear_speed = QtWidgets.QLabel(self.Control)
        self.linear_speed.setGeometry(QtCore.QRect(600, 260, 71, 31))
        self.linear_speed.setObjectName("linear_speed")
        self.label_4 = QtWidgets.QLabel(self.Control)
        self.label_4.setGeometry(QtCore.QRect(530, 550, 81, 31))
        self.label_4.setObjectName("label_4")
        self.angular_Right = QtWidgets.QPushButton(self.Control)
        self.angular_Right.setGeometry(QtCore.QRect(1060, 570, 41, 31))
        self.angular_Right.setObjectName("angular_Right")
        self.angular_left = QtWidgets.QPushButton(self.Control)
        self.angular_left.setGeometry(QtCore.QRect(20, 570, 41, 31))
        self.angular_left.setObjectName("angular_left")
        self.linear_decrease_x = QtWidgets.QPushButton(self.Control)
        self.linear_decrease_x.setGeometry(QtCore.QRect(490, 500, 41, 31))
        self.linear_decrease_x.setObjectName("linear_decrease_x")
        self.linear_increase_x = QtWidgets.QPushButton(self.Control)
        self.linear_increase_x.setGeometry(QtCore.QRect(490, 20, 41, 31))
        self.linear_increase_x.setObjectName("linear_increase_x")
        self.Change_Linear_X_plus = QtWidgets.QDoubleSpinBox(self.Control)
        self.Change_Linear_X_plus.setGeometry(QtCore.QRect(590, 20, 81, 31))
        self.Change_Linear_X_plus.setMinimum(1.0)
        self.Change_Linear_X_plus.setObjectName("Change_Linear_X_plus")
        self.Change_Linear_X_minus = QtWidgets.QDoubleSpinBox(self.Control)
        self.Change_Linear_X_minus.setGeometry(QtCore.QRect(590, 500, 81, 31))
        self.Change_Linear_X_minus.setMinimum(-99.0)
        self.Change_Linear_X_minus.setMaximum(-1.0)
        self.Change_Linear_X_minus.setObjectName("Change_Linear_X_minus")
        self.Change_angular_Z_plus = QtWidgets.QDoubleSpinBox(self.Control)
        self.Change_angular_Z_plus.setGeometry(QtCore.QRect(960, 540, 81, 31))
        self.Change_angular_Z_plus.setMinimum(1.0)
        self.Change_angular_Z_plus.setObjectName("Change_angular_Z_plus")
        self.Change_angular_Z_minus = QtWidgets.QDoubleSpinBox(self.Control)
        self.Change_angular_Z_minus.setGeometry(QtCore.QRect(80, 540, 81, 31))
        self.Change_angular_Z_minus.setMinimum(-99.0)
        self.Change_angular_Z_minus.setMaximum(-1.0)
        self.Change_angular_Z_minus.setObjectName("Change_angular_Z_minus")
        self.camera_streaming_4 = QtWidgets.QLabel(self.Control)
        self.camera_streaming_4.setGeometry(QtCore.QRect(10, 60, 471, 431))
        self.camera_streaming_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.camera_streaming_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.camera_streaming_4.setLineWidth(1)
        self.camera_streaming_4.setText("")
        self.camera_streaming_4.setObjectName("camera_streaming_4")
        self.check_the_box = QtWidgets.QCheckBox(self.Control)
        self.check_the_box.setGeometry(QtCore.QRect(10, 20, 121, 23))
        self.check_the_box.setObjectName("check_the_box")
        self.Check_ping_connection = QtWidgets.QPushButton(self.Control)
        self.Check_ping_connection.setGeometry(QtCore.QRect(970, 120, 131, 25))
        self.Check_ping_connection.setObjectName("Check_ping_connection")
        self.Connection_Status = QtWidgets.QLabel(self.Control)
        self.Connection_Status.setGeometry(QtCore.QRect(770, 20, 41, 21))
        self.Connection_Status.setAutoFillBackground(True)
        self.Connection_Status.setFrameShape(QtWidgets.QFrame.Box)
        self.Connection_Status.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Connection_Status.setText("")
        self.Connection_Status.setObjectName("Connection_Status")
        self.Mac_id = QtWidgets.QLabel(self.Control)
        self.Mac_id.setGeometry(QtCore.QRect(820, 20, 131, 21))
        self.Mac_id.setFrameShape(QtWidgets.QFrame.Box)
        self.Mac_id.setText("")
        self.Mac_id.setObjectName("Mac_id")
        self.lineEdit = QtWidgets.QLineEdit(self.Control)
        self.lineEdit.setGeometry(QtCore.QRect(970, 90, 131, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.SlamLaunch.addTab(self.Control, "")
        self.Odom = QtWidgets.QWidget()
        self.Odom.setObjectName("Odom")
        self.motor1_name = QtWidgets.QLabel(self.Odom)
        self.motor1_name.setGeometry(QtCore.QRect(30, 57, 67, 20))
        self.motor1_name.setObjectName("motor1_name")
        self.motor2_name = QtWidgets.QLabel(self.Odom)
        self.motor2_name.setGeometry(QtCore.QRect(480, 60, 67, 17))
        self.motor2_name.setObjectName("motor2_name")
        self.motor4_name = QtWidgets.QLabel(self.Odom)
        self.motor4_name.setGeometry(QtCore.QRect(480, 310, 67, 17))
        self.motor4_name.setObjectName("motor4_name")
        self.motor3_name = QtWidgets.QLabel(self.Odom)
        self.motor3_name.setGeometry(QtCore.QRect(30, 310, 67, 17))
        self.motor3_name.setObjectName("motor3_name")
        self.Battery_Status = QtWidgets.QProgressBar(self.Odom)
        self.Battery_Status.setGeometry(QtCore.QRect(940, 10, 161, 31))
        self.Battery_Status.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Battery_Status.setProperty("value", 0)
        self.Battery_Status.setObjectName("Battery_Status")
        self.voltage_consumption = QtWidgets.QLCDNumber(self.Odom)
        self.voltage_consumption.setGeometry(QtCore.QRect(940, 100, 161, 51))
        self.voltage_consumption.setObjectName("voltage_consumption")
        self.Current_consumption = QtWidgets.QLCDNumber(self.Odom)
        self.Current_consumption.setGeometry(QtCore.QRect(940, 210, 161, 51))
        self.Current_consumption.setObjectName("Current_consumption")
        self.label = QtWidgets.QLabel(self.Odom)
        self.label.setGeometry(QtCore.QRect(940, 70, 67, 17))
        self.label.setObjectName("label")
        self.label_13 = QtWidgets.QLabel(self.Odom)
        self.label_13.setGeometry(QtCore.QRect(940, 180, 67, 17))
        self.label_13.setObjectName("label_13")
        self.motor_speed_1 = QtWidgets.QLCDNumber(self.Odom)
        self.motor_speed_1.setGeometry(QtCore.QRect(30, 90, 141, 101))
        self.motor_speed_1.setObjectName("motor_speed_1")
        self.ok_motor_3 = QtWidgets.QLabel(self.Odom)
        self.ok_motor_3.setGeometry(QtCore.QRect(190, 370, 109, 49))
        self.ok_motor_3.setFrameShape(QtWidgets.QFrame.Box)
        self.ok_motor_3.setObjectName("ok_motor_3")
        self.ok_motor_1 = QtWidgets.QLabel(self.Odom)
        self.ok_motor_1.setGeometry(QtCore.QRect(190, 120, 109, 49))
        self.ok_motor_1.setFrameShape(QtWidgets.QFrame.Box)
        self.ok_motor_1.setObjectName("ok_motor_1")
        self.ok_motor_2 = QtWidgets.QLabel(self.Odom)
        self.ok_motor_2.setGeometry(QtCore.QRect(640, 120, 109, 49))
        self.ok_motor_2.setFrameShape(QtWidgets.QFrame.Box)
        self.ok_motor_2.setObjectName("ok_motor_2")
        self.ok_motor_4 = QtWidgets.QLabel(self.Odom)
        self.ok_motor_4.setGeometry(QtCore.QRect(640, 370, 109, 49))
        self.ok_motor_4.setFrameShape(QtWidgets.QFrame.Box)
        self.ok_motor_4.setObjectName("ok_motor_4")
        self.motor_speed_4 = QtWidgets.QLCDNumber(self.Odom)
        self.motor_speed_4.setGeometry(QtCore.QRect(480, 340, 141, 101))
        self.motor_speed_4.setObjectName("motor_speed_4")
        self.motor_speed_3 = QtWidgets.QLCDNumber(self.Odom)
        self.motor_speed_3.setGeometry(QtCore.QRect(30, 340, 141, 101))
        self.motor_speed_3.setObjectName("motor_speed_3")
        self.motor_speed_2 = QtWidgets.QLCDNumber(self.Odom)
        self.motor_speed_2.setGeometry(QtCore.QRect(480, 90, 141, 101))
        self.motor_speed_2.setMouseTracking(True)
        self.motor_speed_2.setToolTipDuration(-1)
        self.motor_speed_2.setMode(QtWidgets.QLCDNumber.Dec)
        self.motor_speed_2.setProperty("intValue", 0)
        self.motor_speed_2.setObjectName("motor_speed_2")
        self.Start_map = QtWidgets.QPushButton(self.Odom)
        self.Start_map.setGeometry(QtCore.QRect(300, 490, 111, 71))
        self.Start_map.setObjectName("Start_map")
        self.Save_Map = QtWidgets.QPushButton(self.Odom)
        self.Save_Map.setGeometry(QtCore.QRect(540, 490, 111, 71))
        self.Save_Map.setObjectName("Save_Map")
        self.Map_name_const = QtWidgets.QLabel(self.Odom)
        self.Map_name_const.setGeometry(QtCore.QRect(700, 510, 81, 31))
        self.Map_name_const.setObjectName("Map_name_const")
        self.Map_path_const = QtWidgets.QLabel(self.Odom)
        self.Map_path_const.setGeometry(QtCore.QRect(700, 550, 81, 31))
        self.Map_path_const.setObjectName("Map_path_const")
        self.Note_points = QtWidgets.QLabel(self.Odom)
        self.Note_points.setGeometry(QtCore.QRect(700, 590, 401, 20))
        self.Note_points.setObjectName("Note_points")
        self.Exit_Mapping = QtWidgets.QPushButton(self.Odom)
        self.Exit_Mapping.setGeometry(QtCore.QRect(420, 580, 111, 71))
        self.Exit_Mapping.setObjectName("Exit_Mapping")
        self.Map_name_input = QtWidgets.QLineEdit(self.Odom)
        self.Map_name_input.setGeometry(QtCore.QRect(790, 510, 251, 31))
        self.Map_name_input.setObjectName("Map_name_input")
        self.map_path_input = QtWidgets.QLineEdit(self.Odom)
        self.map_path_input.setGeometry(QtCore.QRect(790, 550, 251, 31))
        self.map_path_input.setObjectName("map_path_input")
        self.SlamLaunch.addTab(self.Odom, "")
        self.horizontalLayout.addWidget(self.SlamLaunch)

        self.retranslateUi(Form)
        self.SlamLaunch.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "APOSTLE"))
        self.linear_stop.setText(_translate("Form", "0"))
        self.angular_stop.setText(_translate("Form", "0"))
        self.control_combo_box.setItemText(0, _translate("Form", "None"))
        self.control_combo_box.setItemText(1, _translate("Form", "/cmd_vel"))
        self.linear_speed.setText(_translate("Form", "0.0 m/s"))
        self.label_4.setText(_translate("Form", "0.0 rad/s"))
        self.angular_Right.setText(_translate("Form", ">"))
        self.angular_left.setText(_translate("Form", "<"))
        self.linear_decrease_x.setText(_translate("Form", "-"))
        self.linear_increase_x.setText(_translate("Form", "+"))
        self.check_the_box.setText(_translate("Form", "Camera Enable"))
        self.Check_ping_connection.setText(_translate("Form", "Check Connection"))
        self.SlamLaunch.setTabText(self.SlamLaunch.indexOf(self.Control), _translate("Form", "Control - Camera"))
        self.motor1_name.setText(_translate("Form", "MOTOR 1"))
        self.motor2_name.setText(_translate("Form", "MOTOR 2"))
        self.motor4_name.setText(_translate("Form", "MOTOR 4"))
        self.motor3_name.setText(_translate("Form", "MOTOR 3"))
        self.label.setText(_translate("Form", "VOLTAGE"))
        self.label_13.setText(_translate("Form", "CURRENT"))
        self.ok_motor_3.setText(_translate("Form", "           OK"))
        self.ok_motor_1.setText(_translate("Form", "           OK"))
        self.ok_motor_2.setText(_translate("Form", "           OK"))
        self.ok_motor_4.setText(_translate("Form", "           OK"))
        self.Start_map.setText(_translate("Form", "Start Mapping"))
        self.Save_Map.setText(_translate("Form", "Save"))
        self.Map_name_const.setText(_translate("Form", "Map Name:"))
        self.Map_path_const.setText(_translate("Form", "Map Path:"))
        self.Note_points.setText(_translate("Form", "NOTE:   Enter the full path, Where map has to be saved"))
        self.Exit_Mapping.setText(_translate("Form", "Exit Mapping"))
        self.SlamLaunch.setTabText(self.SlamLaunch.indexOf(self.Odom), _translate("Form", "Odometry - Battery - SLAM "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
